controller:
  installPlugins:
    - kubernetes:3600.v144b_cd192ca_a_
    - workflow-aggregator:581.v0c46fa_697ffd
    - git:4.11.3
    - configuration-as-code:1429.v09b_044a_c93de
    - job-dsl:1.79
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
       jenkins:
         systemMessage: Welcome to Jenkins, you are. Managed as code, this instance is.
      example-job: |
        jobs:
          - script: >
              multibranchPipelineJob('jenkins-in-kubernetes-example-pipeline') {
                branchSources {
                  git {
                    id('jenkins-in-kubernetes-example-pipeline')  
                    remote('https://github.com/verifa/jenkins-in-kubernetes-example-pipeline.git')
                  }
                }
              }
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "admin"
          name: "Jenkins Admin"
          password: "${chart-admin-password}"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false